// infrastructure/output/css-writer.ts

import fs from 'fs';
import path from 'path';

export class CSSWriter {
  /**
   * Write CSS content to file
   */
  async write(filePath: string, content: string): Promise<void> {
    // Ensure directory exists
    const dir = path.dirname(filePath);
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }

    // Write file
    fs.writeFileSync(filePath, content, 'utf-8');
  }

  /**
   * Generate CSS file with header
   */
  generateFile(content: string, version?: string): string {
    const header = [
      '/**',
      ' * AnubisUI - Auto-generated CSS',
      version ? ` * Version: ${version}` : '',
      ' * DO NOT EDIT THIS FILE MANUALLY',
      ' */',
      '',
    ]
      .filter(Boolean)
      .join('\n');

    return header + content;
  }
}
