import { version } from '../../version';
import { mixinsFile, tokensFile } from '../fileStuff/file.tools';

const header = `/**
 * Anubis v.${version}
 * Improba
 * Released under the MIT License.
 */
@use "${mixinsFile}";
@use "${tokensFile}";
`;

export const mixins = `@use "sass:color";

$background-opacity: (
  10: 0.1,
  20: 0.2,
  30: 0.3,
  40: 0.4,
  50: 0.5,
  60: 0.6,
  70: 0.7,
  80: 0.8,
  90: 0.9
);

// Mixin that will automatically generate colors for light and/or dark themes (with opacity variations)
@mixin setRootColors ($name, $lightColor: null, $darkColor: null) {
  :root {
    @if $lightColor != null {
      body.body--light {
        #{"--"+$name}: $lightColor;

        // Only generate opacity variations for non transparent colors
        @if $lightColor != transparent {
          @each $opacity, $multiplier in $background-opacity {
            #{"--"+$name+"-"+$opacity}: #{color.change($lightColor, $alpha: $multiplier)};
          }
        }
      }
    }

    @if $darkColor != null {
      body.body--dark {
        #{"--"+$name}: $darkColor;

        // Only generate opacity variations for non transparent colors
        @if $darkColor != transparent {
          @each $opacity, $multiplier in $background-opacity {
            #{"--"+$name+"-"+$opacity}: #{color.change($darkColor, $alpha: $multiplier)};
          }
        }
      }
    }
  }
}
`;
export const getHeader = () => {
  return `${header}`;
};


export const comments = {
  colors: `/**
   * These colors will be mapped to css variables in
   * the :root element on the html page.
   *
   * It allows you to write custom css/scss classes in your web
   * components.
   */`,
  
  variations: `/**
   * These css variables are generated automatically when Anubis
   * detects that they are used in utilities in your config.
   *
   * It allows you to write custom css/scss classes in your web
   * components like:
   *
   * .paragraph-small {
   *    font-size: var(--size-xs);
   *    font-weight: var(--weight-light);
   * }
   *
   * (You can also force the generation of all variants from a
   * utility by setting the 'export' to 'variations')
   */`,
  
  rules: `/**
   * These are the css classes generated by Anubis based on your config
   * and what was detected in your source files.
   */`,
} 

/** Map a colorName and hex into mixins function call */
export const defineColor = (colorName: string, light?: string, dark?: string) => {

  const useToken = true

  const lightColor = useToken ? `$${colorName}` : light
  const darkColor = useToken ? `$${colorName}-dark` : dark

  // _ only dark
  if (!light && dark) {
      return `@include setRootColors('${colorName}', null, ${darkColor});`;
  }

  // _ light and/or dark
  return `@include setRootColors('${colorName}', ${[lightColor, darkColor]?.filter(Boolean)?.join(', ')});`;
};

/** Map a color name and hex into token declaration for global usage */
export const defineToken = (colorName: string, light?: string, dark?: string) => {  
  let tokens = []
  
  if (light) {
    tokens.push(`$${colorName}: ${light};`)
    tokens.push(`$${colorName}-light: ${light};`)
  }

  if (dark) {
    tokens.push(`$${colorName}-dark: ${dark};`)
  }

  const stringifiedTokens = tokens?.join('\n')
  return stringifiedTokens
}
