const fs = require('fs');
const path = require('path');

const packageJsonPath = path.join(__dirname, '..', 'package.json');
const versionFilePath = path.join(__dirname, '..', 'src', 'version.ts');

const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf-8'));
const versionCode = `// This file is auto-generated by scripts/generate-version.js
// Do not edit this file manually

export const version = '${packageJson.version}';
export default { version };
`;

fs.writeFileSync(versionFilePath, versionCode, 'utf-8');